#
# use:    JoseQuintas/hbpack/mingw_0703
# create: JoseQuintas/hbpack/mingw_0703
#

name: mingw 7.3

on:
  schedule:
    - cron: '0 0 * * *'

jobs:

  Build:
    runs-on: windows-latest
    steps:
    - name: Load mingw
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: mingw_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/hbpack

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: mingw_0703
         path: c:\temp\mingw_0703.7z
